### ISSUE TITLE
Chrome wont connect to site. Firefox/Terminal can connect

### ISSUE THREAD

**Issue by dogmatic69** [elgalu/docker-selenium#112]
Hi, I seem to have an issue with chrome connecting to my site for testing.
1. Works in firefox through VNC connection to selenium container
2. Works on host chrome (same version, both linux)
3. Can ping / wget URL from terminal in the selenium container
4. Chrome on selenium container can connect to other sites (google, etc)

When trying to access on Chrome there is an error:

```
This site can’t be reached

foo.bar.localhost refused to connect.
Search Google for bar localhost
ERR_CONNECTION_REFUSED
```

DNS

```
application@a31473d2e291:/$ dig foo.bar.localhost           

; <<>> DiG 9.10.3-P4-Ubuntu <<>> foo.bar.localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14067
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;foo.bar.localhost.     IN  A

;; ANSWER SECTION:
foo.bar.localhost.  600 IN  A   172.18.0.4

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Mon Jul 04 16:19:23 CEST 2016
;; MSG SIZE  rcvd: 78
```

I can connect direct to the IP address in chrome

I have looked in the chrome settings and there does not seem to be any DNS config to break this. Anyway its standard out the box install of the repo.

Let me know if you need any other details.

**Comment by elgalu** [comment]
Looks like the problem is that you are using a custom domain name `foo.bar.localhost` probably hard-coded in your `/etc/hosts` file. Try to run the container normally, i.e.

    docker pull elgalu/selenium #upgrades to latest if a newer version is available
    docker run -d --name=grid -p 4444:24444 -p 5900:25900 \
            -e TZ="US/Pacific" -e VNC_PASSWORD=hola \
            -v /dev/shm:/dev/shm elgalu/selenium

But before starting your tests, fix your etc/hosts with the proper IP (in this example I will use `172.17.0.1`)

    docker exec grid sudo bash -c 'echo "172.17.0.1 foo.bar.localhost" >> /etc/hosts'

Now start your tests again, it should properly resolve your foo.bar.localhost

If that doesn't work please include your operating system and docker version.

**Comment by dogmatic69** [comment]
Thanks for the reply. There is no changes to the selenium images as I mentioned above. /etc/hosts is

```
$ cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.5	a31473d2e291
10.0.2.2   my_internal_web_server.local

# This entries help to avoid DNS resolve issue with Sauce Connect
162.222.73.28  saucelabs.com
162.222.76.100 maki76100.miso.saucelabs.com
23.55.155.27   g.symcd.com
172.18.0.1  docker.host
172.18.0.5    docker.guest
172.18.0.1  docker.host.dev
172.18.0.1  d.host.loc.dev
172.18.0.5    docker.guest.dev
172.18.0.1  host.docker.local
172.18.0.5    guest.docker.local
172.18.0.5    d.guest.loc.dev
172.18.0.1  host.docker
172.18.0.5    guest.docker
```

Even if this was the case, why does firefox work correctly. And also curl / ping / wget on the command line work fine.

**Comment by dogmatic69** [comment]
I have manually added the entry to /etc/hosts and that does work. I don't think it should be required though, as it is not for firefox or any other connection.

**Comment by elgalu** [comment]
Maybe your firefox tests do something different and are not testing agains `foo.bar.localhost` ? 

It is required because is a custom domain name that the container is not aware of, try to run it on another machine and you will have the same problem unless you edit the host file or share the dns resolver somehow.

**Comment by elgalu** [comment]
Other moving thing that could be resolving `foo.bar.localhost` would be a PROXY, maybe you use a proxy for firefox but not for chrome.

**Comment by elgalu** [comment]
Ah, also in the next version of docker (1.12) we will be able to add the host in the same `docker run ... --add-host foo.bar.localhost:172.17.0.1 ....`

**Comment by dogmatic69** [comment]
> Maybe your firefox tests do something different and are not testing against foo.bar.localhost ?

No because I am logging into the box using VNC and manually testing both firefox and chrome.

> Other moving thing that could be resolving foo.bar.localhost would be a PROXY, maybe you use a proxy for firefox but not for chrome.

As I have pointed out above, this is a fresh image so I don't see how firefox has proxy and not chrome. Unless that is what you have developed in the repo.

Also I have posted the dig results, showing that the system is able to resolve to internal docker from CLI.

> Ah, also in the next version of docker (1.12) we will be able to add the host in the same

Still does not explain how chrome is the only thing not working

**Comment by elgalu** [comment]
Fair enough. As this gets fixed via hosts I guess we can close this issue. Please open a PR with a reproduceable tests case so we can work from there, see [.travis.yml](https://github.com/elgalu/docker-selenium/blob/master/.travis.yml#L29) and [test/script](https://github.com/elgalu/docker-selenium/blob/master/test/script) . The test should reproduce the issue in TravisCI

**Comment by dogmatic69** [comment]
I have tried with the hosts changes and selenium tests would still not work. Running google-chrome from the command line would work though. 

Seems that there is two versions of chrome installed here.
```
$ which google-chrome
/usr/bin/google-chrome
$ ls -al /opt/google/chrome/chrome
-rwxr-xr-x. 1 root root 103283264 Jun 15 09:55 /opt/google/chrome/chrome
$ ls -al /usr/bin/google-chrome
lrwxrwxrwx. 1 root root 31 Jun 17 20:35 /usr/bin/google-chrome -> /etc/alternatives/google-chrome
$ ls -al /etc/alternatives/google-chrome
lrwxrwxrwx. 1 root root 29 Jun 17 20:35 /etc/alternatives/google-chrome -> /usr/bin/google-chrome-stable
$ ls -al /usr/bin/google-chrome-stable
lrwxrwxrwx. 1 root root 32 Jun 15 09:55 /usr/bin/google-chrome-stable -> /opt/google/chrome/google-chrome
$ ls -al /opt/google/chrome/google-chrome
-rwxrwxr-x. 1 root root 61 Jun 17 20:27 /opt/google/chrome/google-chrome
$ ls -al /opt/google/chrome/google-chrome
-rwxrwxr-x. 1 root root 61 Jun 17 20:27 /opt/google/chrome/google-chrome
```

The file selenium is running is a single 99MB file, 

selenium run / not working (whats up with the unknown in the version number)
```
$ /opt/google/chrome/chrome --version
Google Chrome 51.0.2704.103 unknown
```

manually run / working
```
$ google-chrome --version
Google Chrome 51.0.2704.103
```

**Comment by elgalu** [comment]
Is your host machine Max OSX or Linux or Windows ?

**Comment by shijialee** [comment]
I think this is related to chrome. See this discussion https://bugs.chromium.org/p/chromium/issues/detail?id=489973

**Comment by elgalu** [comment]
Thanks James. 

@dogmatic69 please try to avoid `.localhost` and try something like `.dev`

**Comment by dogmatic69** [comment]
I posted a month ago that I changed the host name being tested...

**Comment by jamsea** [comment]
I'm having the same issue. Tried using `.dev` instead of `.localhost` and Chrome is still complaining that "This site can't be reached". `wget` and Firefox both still work which is super puzzling

**Comment by elgalu** [comment]
Was anyone able to solve this?

**Comment by elgalu** [comment]
Closing as stale.

**Comment by windowuser121** [comment]
Here is how to fix ERR_CONNECTION_REFUSED In Chrome
Open Command Prompt in the administrator mode. You can do so by right clicking on the CMD program and then by clicking on the Run as administrator option as shown in the screenshot given below.
As next, type in or copy-paste the following commands one by one into the CMD. Don’t forget to hit enter after each command.
ipconfig /all
ipconfig /flushdns
ipconfig /renew
netsh int ip set dns
netsh winsock reset
ipconfig /release
Once you are all done, restart your PC to get rid of the ERR_CONNECTION_REFUSED error.
Source:- [](http://merabheja.com/fix-err_connection_refused-chrome/)

**Comment by normanfrancis** [comment]
I came across this issue recently and as @elgalu said, you should avoid using localhost.

However, you should also avoid using .dev now as it's a [valid TLD.](https://superuser.com/questions/1303396/how-to-fix-firefox-59-no-longer-accepting-my-self-signed-ssl-certificate-on-dev/1303530#1303530) , and the browser will complain about self-signed certficates.

I ended up using .local but if you run into a similar issue I suggest checking if you're trying to use a valid TLD
